# Librerias
```{r}
library(readxl)
library(rpart)
library(randomForest)
```

# Datos
```{r}
data <- read_excel("..\\datos.xlsx")

datar <- data[, c("AGR_TRABAJA", "VIC_SEXO", "VIC_EDAD", "VIC_ESCOLARIDAD", "VIC_EST_CIV", "VIC_TRABAJA")]

datar$AGR_TRABAJA <- as.factor(datar$AGR_TRABAJA)

# Quitar datos nulos
datar <- na.omit(datar)

# Aleatorizar la información
set.seed(100)

# Revolver toda la informacion para no sesgar resultados
datar <- datar[sample(1:nrow(datar)), ]

# Definir datos de entreno (80%) y testeo (20%)
index <- sample(1:nrow(datar), 0.8 * nrow(datar))

train <- datar[index, ]
test <- datar[-index, ]
```

# Random Forest
```{r}
bosque <- randomForest(AGR_TRABAJA ~
                 VIC_SEXO +
                 VIC_EDAD +
                 VIC_ESCOLARIDAD + 
                 VIC_TRABAJA,
               data = train, 
               ntree = 100,
               mtry = 4
             )

# Probar el bosque con el 20% restante
prueba <- predict(bosque, test)

matriz <- table(test$AGR_TRABAJA, prueba)

precision <- sum(diag(matriz)) / sum(matriz)

precision  # 69.25%
```

# Predicciones
```{r}
# Victima 1
victima_1 <- data.frame(
  VIC_SEXO = c(2),
  VIC_EDAD = c(25),
  VIC_ESCOLARIDAD = c(49),
  VIC_EST_CIV = c(1),
  VIC_TRABAJA= c(2)
)

# Victima 2
victima_2 <- data.frame(
  VIC_SEXO = c(1),
  VIC_EDAD = c(18),
  VIC_ESCOLARIDAD = c(39),
  VIC_EST_CIV = c(1),
  VIC_TRABAJA= c(1)
)

# Victima 3
victima_3 <- data.frame(
  VIC_SEXO = c(2),
  VIC_EDAD = c(50),
  VIC_ESCOLARIDAD = c(59),
  VIC_EST_CIV = c(2),
  VIC_TRABAJA= c(2)
)

r_prediccion_1 = predict(bosque, victima_1, type="prob")
r_prediccion_1

r_prediccion_2 = predict(bosque, victima_2, type="prob")
r_prediccion_2

r_prediccion_3 = predict(bosque, victima_3, type="prob")
r_prediccion_3
```


# Graficación
```{r}
plot(bosque)
```

