# Librerias
```{r}
library(arules)
library(ggplot2)
library(readxl)
library(ggalt)
```

# Datos
```{r}
data <- read_excel("C:\\Users\\luisf\\OneDrive\\Documentos\\USAC\\POSTGRADO\\TR4\\Mineria de datos\\IntroduccionMineriaDatos\\T4\\datos.xlsx")

data_f <- data[, c("HEC_DEPTO", "VIC_EDAD")]

data_f <- subset(data_f, HEC_DEPTO != 99 & HEC_DEPTO != -1 & HEC_DEPTO != 100 & VIC_EDAD != 99 & VIC_EDAD != 100)

# Limpieza de valores nulos
data_f[is.na(data_f)] <- -1
```


# Clustering
```{r}
cluster <- kmeans(data_f, centers = 4)

ggplot(data_f, aes(x = HEC_DEPTO, y = VIC_EDAD, color = as.factor(cluster$cluster), shape = as.factor(cluster$cluster))) +
  geom_point(size = 3, alpha = 0.7) +                                   
  geom_point(data = as.data.frame(cluster$centers),                    
             aes(x = HEC_DEPTO, y = VIC_EDAD), color = "black", fill = "yellow", size = 5, shape = 21) +
  geom_encircle(aes(group = cluster$cluster, fill = as.factor(cluster$cluster)), 
                alpha = 0.2, s_shape = 1, expand = 0.05) +              
  scale_color_manual(values = c("red", "green", "blue", "purple")) +
  scale_shape_manual(values = c(16, 17, 15, 18)) +
  #scale_x_continuous(breaks = seq(min(data_f$QUIEN_REPORTA), max(data_f$QUIEN_REPORTA), by = 1)) +
  #scale_y_continuous(breaks = seq(min(data_f$DEPTO_MCPIO), max(data_f$DEPTO_MCPIO), by = 1)) +
  labs(title = "Departamento vs Edad víctima", x = "Departamento", y = "Edad víctima") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "right",
    legend.title = element_blank()
  )
```